### ISSUE TITLE
mask or alpha channel support

### ISSUE THREAD

**Issue by dvoidus** [ArthurBrussee/brush#13]
First of all -- great work! keep on working on the project, we need more tools like this one.

I normally "clean" my dataset before training a splat by removing background and only keep pixels of an object I'm training.
Resulting dataset is in png format with alpha channel.

My approach works great with Postshot, but training wont work with brush, it looks like it only does one epoch, creating initial splat properties and than wont continue training without any error message or any other notification.

Can you comment on alpha channel support or may be mask support for training (really helps to focus process on pixels of the actual object you train, rather than background and save tone of time as there are no need to do cleaning after training).

BTW any plans to improve training speed?

**Comment by dvoidus** [comment]
```
     Running `target\debug\brush_bin.exe`
thread 'async-std/runtime' panicked at .cargo\git\checkouts\burn-178c6829f420dae1\9eb2578\crates\burn-tensor\src\tensor\data.rs:72:9:
assertion `left == right` failed: Shape [1920, 1080, 4] is invalid for input of size 6220800
  left: 8294400
 right: 6220800
```

**Comment by dvoidus** [comment]
image_to_tensor in brush_train\src\image.rs needs to be tweaked a bit:

```
pub fn image_to_tensor<B: Backend>(image: &DynamicImage, device: &B::Device) -> Tensor<B, 3> {
    let (w, h) = (image.width(), image.height());
    let num_channels = image.color().channel_count();

    let data = match num_channels {
        3 => image.to_rgb32f().into_vec(),
        4 => image.to_rgba32f().into_vec(),
        _ => {
            println!("Unsupported number of channels: {}. Converting to RGB.", num_channels);
            image.to_rgb32f().into_vec() // Convert to RGB as a fallback
        }
    };

    let tensor_data = TensorData::new(data, [h as usize, w as usize, num_channels as usize]);
    Tensor::from_data(tensor_data, device)
}
```

**Comment by dvoidus** [comment]
but it still seems to be ignoring alpha...

and I frequently get crashes:
```
> cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.90s
     Running `target\debug\brush_bin.exe`
error: process didn't exit successfully: `target\debug\brush_bin.exe` (exit code: 0xc0000094, STATUS_INTEGER_DIVIDE_BY_ZERO)
```

**Comment by dvoidus** [comment]
> Lmk if that's working!

Did a quick test, it works now!

Need to do more testing but at first glance its good.
One thing I've noticed though is that dataset image view now always keeps square aspect ratio and weirdly ruins photo view proportions

**Comment by ArthurBrussee** [comment]
@grgkopanas That's how it used to work! But imo you're still throwing information in that case. Say for the synthetic blender scenes with a white background, white gaussians would appear which for one viewpoint explain some of the background, which isn't ideal. There's more info in the fact that the alpha should be 0 there.

Gsplat used to always composite a background and add custom gradients for that, but now also has an option to render without compositing a background, makes more sense to me.

I maybe should add an option for random backgrounds again, but, that could be done as a normal tensor op rather than compositing in the custom kernel, shouldn't be super expensive.

@dvoidus Excellent! And woops yeah I see what you mean, fixed now.

**Comment by dvoidus** [comment]
> fixed now
tested, confirm
@ArthurBrussee thanks! feel free to close this one or keep for further discussion about alpha channel training
