### ISSUE TITLE
Export failed

### ISSUE THREAD

**Issue by fasteinke** [ArthurBrussee/brush#72]
Latest source ... training working well, couple of divide by zero fails, but live update off is a workaround. But, got this:

D:\Apps\brush-main>cargo run
    Finished `dev` profile [optimized + debuginfo] target(s) in 2.39s
     Running `target\debug\brush_app.exe`
thread 'main' panicked at C:\Users\fstei\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-core-23.0.1\src\resource.rs:749:59:
thread 'main' attempted to acquire a snatch lock recursively.
- Currently trying to acquire a write lock at C:\Users\fstei\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-core-23.0.1\src\resource.rs:749:59
disabled backtrace
- Previously acquired a read lock at C:\Users\fstei\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-core-23.0.1\src\device\queue.rs:969:60
disabled backtrace
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\brush_app.exe` (exit code: 101)

Edit: the export _did_ actually work, with a good ply; but can't continue. of course. An init.ply would be a workaround ...

**Comment by ArthurBrussee** [comment]
I think this error is basically still due to whatever is causing the divide_by_zero whatever crash. It leaves wgpu in an invalid state (_even_ after restarting the app... until some process in Vulkan restarts). Closing this in favour of the big uber divide by zero bug.

And yeah to continue training rename a checkpoint to init.ply - will have to make that all a bit smoother later.
